name: Build Production

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-13, ubuntu-20.04, windows-2022]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-node@master
      with:
        node-version: 18
    - name: install dependencies
      run: npm install
    - name: Install appdmg on macOS
      if: matrix.os == 'macos-13'
      run: npm install --save-dev appdmg
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npm run publish

  
